/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class navigate_Navigate */

#ifndef _Included_navigate_Navigate
#define _Included_navigate_Navigate
#ifdef __cplusplus
extern "C" {
#endif
#undef navigate_Navigate_TurnLeft
#define navigate_Navigate_TurnLeft 3L
#undef navigate_Navigate_TurnRight
#define navigate_Navigate_TurnRight 4L
#undef navigate_Navigate_WalkDirect
#define navigate_Navigate_WalkDirect 5L
#undef navigate_Navigate_WalkAlong
#define navigate_Navigate_WalkAlong 6L
#undef navigate_Navigate_Arrive
#define navigate_Navigate_Arrive 11L
/*
 * Class:     navigate_Navigate
 * Method:    loadPathInfo
 * Signature: (Ljava/lang/String;)[Lnavigate/Point;
 */
JNIEXPORT jobjectArray JNICALL Java_navigate_Navigate_loadPathInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     navigate_Navigate
 * Method:    getBestPath
 * Signature: (Lnavigate/Point;Lnavigate/Point;)[Lnavigate/Point;
 */
JNIEXPORT jobjectArray JNICALL Java_navigate_Navigate_getBestPath
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
