/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_bukp_testrssi_JniBridge */

#ifndef _Included_me_bukp_testrssi_JniBridge
#define _Included_me_bukp_testrssi_JniBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_bukp_testrssi_JniBridge
 * Method:    loadWifiFinger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_me_bukp_testrssi_JniBridge_loadWifiFinger
  (JNIEnv *, jclass, jstring);

/*
 * Class:     me_bukp_testrssi_JniBridge
 * Method:    doLocate
 * Signature: (Ljava/lang/String;)Lme/bukp/testrssi/Point;
 */
JNIEXPORT jobject JNICALL Java_me_bukp_testrssi_JniBridge_doLocate
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
