/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_bukp_pakamaplib_business_PakaCoreJniBridge */

#ifndef _Included_me_bukp_pakamaplib_business_PakaCoreJniBridge
#define _Included_me_bukp_pakamaplib_business_PakaCoreJniBridge
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     me_bukp_pakamaplib_business_PakaCoreJniBridge
 * Method:    just4T
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_bukp_pakamaplib_business_PakaCoreJniBridge_just4T
  (JNIEnv *, jobject);

/*
 * Class:     me_bukp_pakamaplib_business_PakaCoreJniBridge
 * Method:    loadPathInfo
 * Signature: (Ljava/lang/String;)[Lme/bukp/pakamaplib/business/Point;
 */
JNIEXPORT jobjectArray JNICALL Java_me_bukp_pakamaplib_business_PakaCoreJniBridge_loadPathInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     me_bukp_pakamaplib_business_PakaCoreJniBridge
 * Method:    getBestPath
 * Signature: (Lme/bukp/pakamaplib/business/Point;Lme/bukp/pakamaplib/business/Point;)[Lme/bukp/pakamaplib/business/Point;
 */
JNIEXPORT jobjectArray JNICALL Java_me_bukp_pakamaplib_business_PakaCoreJniBridge_getBestPath
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
